name = "NonparametricCognitiveDiagnosisModel"
uuid = "506f3bee-758e-40a7-86de-9c6e62f9cb49"
version = "0.1.0"
authors = ["allen19970828 <122233643+allen19970828@users.noreply.github.com>"]
description = "High-performance Julia package for Cognitive Diagnosis Models (CDMs), featuring NCDM, Q-matrix refinement, MLE/JMLE for DINA, DINO, NIDA, GNIDA, RRUM, and the novel Nonparametric Weighted CDM (NWCDM) with high-precision box-constrained optimization."

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1"
LinearAlgebra = "1.12.0"
NLsolve = "4.5.1"
Optim = "1.13.3"
RecipesBase = "1.3.4"
SpecialFunctions = "2.7.2"
Statistics = "1.11.1"
StatsBase = "0.34.10"
